version: '3'

services:
  db:
    image: docker.io/library/postgres:14
    container_name: nextcloud_db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=comet
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=mecha
    networks:
      - demo-net

  app:
    image: docker.io/library/nextcloud:latest
    container_name: nextcloud_app
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - POSTGRES_HOST=nextcloud_db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=mecha
      - POSTGRES_PASSWORD=comet

    networks:
      - demo-net

volumes:
  db_data:
  nextcloud_data:

networks:
  demo-net:
    name: demo-net
    external: true
