version: '3'

services:
  uptime-kuma:
    image: docker.io/louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
    ports:
      - "3001:3001"
    restart: always
    networks:
      - demo-net

networks:
  demo-net:
    name: demo-net
    external: true
